#ifndef KB_SCANCODE_SET2
#define KB_SCANCODE_SET2

/* ================================================================= */
//PRESSED KEYS
/* ================================================================= */

#define KB_SC_PRESSED_NOTHING 0x00
#define KB_SC_PRESSED_ESCAPE  0x01
#define KB_SC_PRESSED_ONE     0x02
#define KB_SC_PRESSED_TWO     0x03
#define KB_SC_PRESSED_THREE   0x04
#define KB_SC_PRESSED_FOUR    0x05
#define KB_SC_PRESSED_FIVE    0x06
#define KB_SC_PRESSED_SIX     0x07
#define KB_SC_PRESSED_SEVEN   0x08
#define KB_SC_PRESSED_EIGHT   0x09
#define KB_SC_PRESSED_NINE    0x0A
#define KB_SC_PRESSED_ZERO    0x0B

#define KB_SC_PRESSED_DASH        0x0C
#define KB_SC_PRESSED_EQUAL       0x0D
#define KB_SC_PRESSED_BACKSPACE   0x0E
#define KB_SC_PRESSED_TAB         0x0F

#define KB_SC_PRESSED_Q   0x10
#define KB_SC_PRESSED_W   0x11
#define KB_SC_PRESSED_E   0x12
#define KB_SC_PRESSED_R   0x13
#define KB_SC_PRESSED_T   0x14
#define KB_SC_PRESSED_Y   0x15
#define KB_SC_PRESSED_U   0x16
#define KB_SC_PRESSED_I   0x17
#define KB_SC_PRESSED_O   0x18
#define KB_SC_PRESSED_P   0x19

#define KB_SC_PRESSED_LEFT_SQ_BRACKETS    0x1A
#define KB_SC_PRESSED_RIGHT_SQ_BRACKETS   0x1B
#define KB_SC_PRESSED_ENTER               0x1C
#define KB_SC_PRESSED_LEFT_CTRL           0x1D

#define KB_SC_PRESSED_A 0x1E
#define KB_SC_PRESSED_S 0x1F
#define KB_SC_PRESSED_D 0x20
#define KB_SC_PRESSED_F 0x21
#define KB_SC_PRESSED_G 0x22
#define KB_SC_PRESSED_H 0x23
#define KB_SC_PRESSED_J 0x24
#define KB_SC_PRESSED_K 0x25
#define KB_SC_PRESSED_L 0x26

#define KB_SC_PRESSED_SEMICOLON    0x27
#define KB_SC_PRESSED_SINGLE_QUOTE 0x28
#define KB_SC_PRESSED_BACK_TICK    0x29
#define KB_SC_PRESSED_LEFT_SHIFT   0x2A
#define KB_SC_PRESSED_BACKSLASH    0x2B

#define KB_SC_PRESSED_Z 0x2C
#define KB_SC_PRESSED_X 0x2D
#define KB_SC_PRESSED_C 0x2E
#define KB_SC_PRESSED_V 0x2F
#define KB_SC_PRESSED_B 0x30
#define KB_SC_PRESSED_N 0x31
#define KB_SC_PRESSED_M 0x32

#define KB_SC_PRESSED_COMMA       0x33
#define KB_SC_PRESSED_DOT         0x34
#define KB_SC_PRESSED_SLASH       0x35
#define KB_SC_PRESSED_RIGHT_SHIFT 0x36
#define KB_SC_PRESSED_KEYPAD_MULT 0x37
#define KB_SC_PRESSED_LEFT_ALT    0x38
#define KB_SC_PRESSED_SPACE       0x39
#define KB_SC_PRESSED_CAPS_LOCK   0x3A
#define KB_SC_PRESSED_F1          0x3B
#define KB_SC_PRESSED_F2          0x3C
#define KB_SC_PRESSED_F3          0x3D
#define KB_SC_PRESSED_F4          0x3E
#define KB_SC_PRESSED_F5          0x3F
#define KB_SC_PRESSED_F6          0x40
#define KB_SC_PRESSED_F7          0x41
#define KB_SC_PRESSED_F8          0x42
#define KB_SC_PRESSED_F9          0x43
#define KB_SC_PRESSED_F10         0x44
#define KB_SC_PRESSED_F11         0x57
#define KB_SC_PRESSED_F12         0x58
#define KB_SC_PRESSED_NUMLOCK     0x45
#define KB_SC_PRESSED_SCROLL_LOCK 0x46

#define KB_SC_PRESSED_KEYPAD_SEVEN  0x47
#define KB_SC_PRESSED_KEYPAD_EIGHT  0x48
#define KB_SC_PRESSED_KEYPAD_NINE   0x49
#define KB_SC_PRESSED_KEYPAD_MINUS  0x4A
#define KB_SC_PRESSED_KEYPAD_FOUR   0x4B
#define KB_SC_PRESSED_KEYPAD_FIVE   0x4C
#define KB_SC_PRESSED_KEYPAD_SIX    0x4D
#define KB_SC_PRESSED_KEYPAD_PLUS   0x4E
#define KB_SC_PRESSED_KEYPAD_ONE    0x4F
#define KB_SC_PRESSED_KEYPAD_TWO    0x50
#define KB_SC_PRESSED_KEYPAD_THREE  0x51
#define KB_SC_PRESSED_KEYPAD_ZERO   0x52
#define KB_SC_PRESSED_KEYPAD_DOT    0x53

/* ================================================================= */
// RELEASED KEYS
/* ================================================================= */

#define KB_SC_RELEASED_NOTHING 0x80
#define KB_SC_RELEASED_ESCAPE  0x81
#define KB_SC_RELEASED_ONE     0x82
#define KB_SC_RELEASED_TWO     0x83
#define KB_SC_RELEASED_THREE   0x84
#define KB_SC_RELEASED_FOUR    0x85
#define KB_SC_RELEASED_FIVE    0x86
#define KB_SC_RELEASED_SIX     0x87
#define KB_SC_RELEASED_SEVEN   0x88
#define KB_SC_RELEASED_EIGHT   0x89
#define KB_SC_RELEASED_NINE    0x8A
#define KB_SC_RELEASED_ZERO    0x8B

#define KB_SC_RELEASED_DASH        0x8C
#define KB_SC_RELEASED_EQUAL       0x8D
#define KB_SC_RELEASED_BACKSPACE   0x8E
#define KB_SC_RELEASED_TAB         0x8F

#define KB_SC_RELEASED_Q   0x90
#define KB_SC_RELEASED_W   0x91
#define KB_SC_RELEASED_E   0x92
#define KB_SC_RELEASED_R   0x93
#define KB_SC_RELEASED_T   0x94
#define KB_SC_RELEASED_Y   0x95
#define KB_SC_RELEASED_U   0x96
#define KB_SC_RELEASED_I   0x97
#define KB_SC_RELEASED_O   0x98
#define KB_SC_RELEASED_P   0x99

#define KB_SC_RELEASED_LEFT_SQ_BRACKETS    0x9A
#define KB_SC_RELEASED_RIGHT_SQ_BRACKETS   0x9B
#define KB_SC_RELEASED_ENTER               0x9C
#define KB_SC_RELEASED_LEFT_CTRL           0x9D

#define KB_SC_RELEASED_A 0x9E
#define KB_SC_RELEASED_S 0x9F
#define KB_SC_RELEASED_D 0xA0
#define KB_SC_RELEASED_F 0xA1
#define KB_SC_RELEASED_G 0xA2
#define KB_SC_RELEASED_H 0xA3
#define KB_SC_RELEASED_J 0xA4
#define KB_SC_RELEASED_K 0xA5
#define KB_SC_RELEASED_L 0xA6

#define KB_SC_RELEASED_SEMICOLON    0xA7
#define KB_SC_RELEASED_SINGLE_QUOTE 0xA8
#define KB_SC_RELEASED_BACK_TICK    0xA9
#define KB_SC_RELEASED_LEFT_SHIFT   0xAA
#define KB_SC_RELEASED_BACKSLASH    0xAB

#define KB_SC_RELEASED_Z 0xAC
#define KB_SC_RELEASED_X 0xAD
#define KB_SC_RELEASED_C 0xAE
#define KB_SC_RELEASED_V 0xAF
#define KB_SC_RELEASED_B 0xB0
#define KB_SC_RELEASED_N 0xB1
#define KB_SC_RELEASED_M 0xB2

#define KB_SC_RELEASED_COMMA       0xB3
#define KB_SC_RELEASED_DOT         0xB4
#define KB_SC_RELEASED_SLASH       0xB5
#define KB_SC_RELEASED_RIGHT_SHIFT 0xB6
#define KB_SC_RELEASED_KEYPAD_MULT 0xB7
#define KB_SC_RELEASED_LEFT_ALT    0xB8
#define KB_SC_RELEASED_SPACE       0xB9
#define KB_SC_RELEASED_CAPS_LOCK   0xBA
#define KB_SC_RELEASED_F1          0xBB
#define KB_SC_RELEASED_F2          0xBC
#define KB_SC_RELEASED_F3          0xBD
#define KB_SC_RELEASED_F4          0xBE
#define KB_SC_RELEASED_F5          0xBF
#define KB_SC_RELEASED_F6          0xC0
#define KB_SC_RELEASED_F7          0xC1
#define KB_SC_RELEASED_F8          0xC2
#define KB_SC_RELEASED_F9          0xC3
#define KB_SC_RELEASED_F10         0xC4
#define KB_SC_RELEASED_F11         0xD7
#define KB_SC_RELEASED_F12         0xD8
#define KB_SC_RELEASED_NUMLOCK     0xC5
#define KB_SC_RELEASED_SCROLL_LOCK 0xC6

#define KB_SC_RELEASED_KEYPAD_SEVEN  0xC7
#define KB_SC_RELEASED_KEYPAD_EIGHT  0xC8
#define KB_SC_RELEASED_KEYPAD_NINE   0xC9
#define KB_SC_RELEASED_KEYPAD_MINUS  0xCA
#define KB_SC_RELEASED_KEYPAD_FOUR   0xCB
#define KB_SC_RELEASED_KEYPAD_FIVE   0xCC
#define KB_SC_RELEASED_KEYPAD_SIX    0xCD
#define KB_SC_RELEASED_KEYPAD_PLUS   0xCE
#define KB_SC_RELEASED_KEYPAD_ONE    0xCF
#define KB_SC_RELEASED_KEYPAD_TWO    0xD0
#define KB_SC_RELEASED_KEYPAD_THREE  0xD1
#define KB_SC_RELEASED_KEYPAD_ZERO   0xD2
#define KB_SC_RELEASED_KEYPAD_DOT    0xD3

#endif
